image: alpine/edge
packages:
  - go
sources:
  - https://git.sr.ht/~skuzzymiglet/feef
tasks:
  - build: |
      cd feef
      go build .
image: openbsd/latest
packages:
  - go
sources:
  - https://git.sr.ht/~skuzzymiglet/feef
tasks:
  - build: |
      cd feef
      go build .
image: debian/unstable
arch: arm64
packages:
  - golang-1.15
sources:
  - https://git.sr.ht/~skuzzymiglet/feef
tasks:
  - build: |
      cd feef
       /usr/lib/go-1.15/bin/go build .
