image: alpine/edge
artifacts:
  - feef/dist/feef-linux-amd64
  - feef/dist/feef-linux-386
  - feef/dist/feef-linux-arm64
  - feef/dist/feef-windows-amd64.exe
packages:
  - go
  - zip
sources:
  - https://git.sr.ht/~skuzzymiglet/feef
tasks:
  - test: |
      cd feef
      go test -v -cover -race
  - builds: |
      cd feef
      go build -v
