#!/bin/bash

# RSS reader, using fzf
# dependencies: feef, bash, xargs, xdg-open (or set OPENER), wget (or set DOWNLOADER), fzf

set -euo pipefail

open="${OPENER:-xdg-open}"
download="${DOWNLOADER:-wget}"

time='{{ if .PublishedParsed}}{{.PublishedParsed | datef "02/01" }}{{else}}??/??{{end}}'
fmt="$time {{trunc 10 .Feed.Title}}: {{.Title}} @ {{.Link}} ({{.GUID}})"
fzf_binds="enter:execute-silent(cut -d@ -f2- <<< {} | xargs $open &),tab:toggle-sort,ctrl-d:execute-silent(cut -d@ -f2- <<< {} | xargs $download &)"

(feef -s -r 1m -f "$fmt" && feef -n new -r 1m -f "$fmt") | fzf --no-mouse --bind "$fzf_binds"
